package main

// dummy cert valid until 2028-12-18T07:57:25Z

const (
	dummyCert = `-----BEGIN CERTIFICATE-----
MIIBpTCCASygAwIBAgIQDsTUCPYmLiljAbeoyAHYKjAKBggqhkjOPQQDAzAbMRkw
FwYDVQQKExBwcm9tc3dhcm1jb25uZWN0MB4XDTE4MTIyMTA2NTcyNVoXDTI4MTIx
ODA3NTcyNVowGzEZMBcGA1UEChMQcHJvbXN3YXJtY29ubmVjdDB2MBAGByqGSM49
AgEGBSuBBAAiA2IABLljHLrnXRQDnr6OseBV/a4PKcHN4aQ38k/LFxYIbiFGKrj5
GRyrCepMloKt5tNW6Rx3y3AYoupQ9Gs5mKEPC6zgYLPV++C8VfAeldbFYWz54Rwu
O3yTgIMPqC9rwYApRqM1MDMwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsG
AQUFBwMBMAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwMDZwAwZAIwB0cZRz8oenm9
p7VGsEvI8ZjEyp9FH/4fnWCyTqYiy5FE95rkPBpeAGddvTnfgFfOAjB9Ls6xxJNo
BhdLAfTZ1VAElbsDqoBID9mpKHmsq+G+EASGGBEWpQiQz5P52KL+ryg=
-----END CERTIFICATE-----`
	dummyCertKey = `-----BEGIN EC PRIVATE KEY-----
MIGkAgEBBDArRRWPn6/SAyDjGXIzIr5Z1/EuTGcJdq05QULZk5oWJ3e9nb0TPJCr
h2xXdfKux9+gBwYFK4EEACKhZANiAAS5Yxy6510UA56+jrHgVf2uDynBzeGkN/JP
yxcWCG4hRiq4+RkcqwnqTJaCrebTVukcd8twGKLqUPRrOZihDwus4GCz1fvgvFXw
HpXWxWFs+eEcLjt8k4CDD6gva8GAKUY=
-----END EC PRIVATE KEY-----`
)
